import { Router } from "express";
import { Op } from "sequelize";
import { asyncHandler, ApiError } from "../../core/errors.js";
import { authenticate } from "../auth/auth.js";
import { audit, requirePermission } from "../../security/authorization.js";
import { PERMISSIONS } from "../../security/permissions.js";
import { db } from "../../models/index.js";
import { accessState, assertGradebookScope, clearManualCompletion, gradebookForStudent, progressForCourse, recordCompletion, savePrerequisite } from "./completion-gradebook.service.js";

const send = (res, data, status = 200) => res.status(status).json({ data });
const cleanComment = (value) => { const text = String(value || "").replace(/<[^>]*>/g, "").trim(); if (!text || text.length > 5000) throw new ApiError(422, "Comment must be between 1 and 5000 characters"); return text; };
const router = Router();

router.get("/student/activities/:activityId/access-state", authenticate, asyncHandler(async (req, res) => send(res, await accessState(req.user.sub, req.params.activityId))));
router.get("/student/courses/:courseTrackId/progress", authenticate, asyncHandler(async (req, res) => { const enrolled = await db.Enrolment.findOne({ where: { userId: req.user.sub, courseTrackId: req.params.courseTrackId, status: "active" } }); if (!enrolled) throw new ApiError(403, "Course enrollment is required"); send(res, await progressForCourse(req.user.sub, req.params.courseTrackId)); }));
router.get("/student/courses/:courseTrackId/gradebook", authenticate, asyncHandler(async (req, res) => { const enrolled = await db.Enrolment.findOne({ where: { userId: req.user.sub, courseTrackId: req.params.courseTrackId, status: "active" } }); if (!enrolled) throw new ApiError(403, "Course enrollment is required"); send(res, await gradebookForStudent(req.user.sub, req.params.courseTrackId)); }));
router.post("/student/activities/:activityId/manual-completion", authenticate, asyncHandler(async (req, res) => { const activity = await db.LessonSection.findByPk(req.params.activityId); if (!activity || activity.completionMode !== "manual") throw new ApiError(422, "This activity does not support manual completion"); const state = await accessState(req.user.sub, req.params.activityId); if (state.locked) throw new ApiError(403, "Activity prerequisites are not met"); send(res, await recordCompletion(req.user.sub, req.params.activityId, "manual")); }));
router.delete("/student/activities/:activityId/manual-completion", authenticate, asyncHandler(async (req, res) => { await clearManualCompletion(req.user.sub, req.params.activityId); res.status(204).end(); }));

router.get("/admin/activities/:activityId/completion-settings", authenticate, requirePermission(PERMISSIONS.ACTIVITIES_READ), asyncHandler(async (req, res) => { const activity = await db.LessonSection.findByPk(req.params.activityId); if (!activity) throw new ApiError(404, "Activity not found"); await assertGradebookScope(req.user, (await db.Lesson.findByPk(activity.lessonId)).trackId, "canManageContent"); send(res, { completionMode: activity.completionMode, combination: "all", prerequisites: await db.ActivityPrerequisite.findAll({ where: { activityId: activity.id }, order: [["sortOrder", "ASC"]] }) }); }));
router.patch("/admin/activities/:activityId/completion-settings", authenticate, requirePermission(PERMISSIONS.ACTIVITIES_UPDATE), asyncHandler(async (req, res) => { const activity = await db.LessonSection.findByPk(req.params.activityId); if (!activity) throw new ApiError(404, "Activity not found"); const lesson = await db.Lesson.findByPk(activity.lessonId); await assertGradebookScope(req.user, lesson.trackId, "canManageContent"); const allowed = activity.type === "quiz" ? ["none", "view", "manual", "submit", "pass"] : activity.type === "assignment" ? ["none", "view", "manual", "submit", "pass"] : ["none", "view", "manual"]; if (!allowed.includes(req.body.completionMode)) throw new ApiError(422, "Completion mode is not valid for this activity type"); await activity.update({ completionMode: req.body.completionMode }); await audit(req, "activity_completion_settings_updated", "activity", activity.id, { completionMode: activity.completionMode }); send(res, { completionMode: activity.completionMode, combination: "all" }); }));
router.post("/admin/activities/:activityId/prerequisites", authenticate, requirePermission(PERMISSIONS.ACTIVITIES_UPDATE), asyncHandler(async (req, res) => { const rule = await savePrerequisite(req.user, req.params.activityId, req.body); await audit(req, "activity_prerequisite_created", "activity_prerequisite", rule.id, { activityId: req.params.activityId }); send(res, rule, 201); }));
router.patch("/admin/activity-prerequisites/:id", authenticate, requirePermission(PERMISSIONS.ACTIVITIES_UPDATE), asyncHandler(async (req, res) => { const current = await db.ActivityPrerequisite.findByPk(req.params.id); if (!current) throw new ApiError(404, "Prerequisite not found"); const rule = await savePrerequisite(req.user, current.activityId, req.body, current.id); await audit(req, "activity_prerequisite_updated", "activity_prerequisite", rule.id); send(res, rule); }));
router.delete("/admin/activity-prerequisites/:id", authenticate, requirePermission(PERMISSIONS.ACTIVITIES_UPDATE), asyncHandler(async (req, res) => { const rule = await db.ActivityPrerequisite.findByPk(req.params.id); if (!rule) throw new ApiError(404, "Prerequisite not found"); const activity = await db.LessonSection.findByPk(rule.activityId); await assertGradebookScope(req.user, (await db.Lesson.findByPk(activity.lessonId)).trackId, "canManageContent"); await rule.destroy(); await audit(req, "activity_prerequisite_deleted", "activity_prerequisite", rule.id); res.status(204).end(); }));

router.get("/admin/courses/:courseTrackId/gradebook", authenticate, requirePermission(PERMISSIONS.GRADES_READ), asyncHandler(async (req, res) => { await assertGradebookScope(req.user, req.params.courseTrackId); const page = Math.max(1, Number(req.query.page) || 1), limit = Math.min(100, Math.max(1, Number(req.query.limit) || 25)); const where = { courseTrackId: req.params.courseTrackId, status: "active" }; const users = await db.Enrolment.findAll({ where, include: [{ model: db.User, where: req.query.search ? { [Op.or]: [{ name: { [Op.like]: `%${req.query.search}%` } }, { email: { [Op.like]: `%${req.query.search}%` } }] } : {}, attributes: ["id", "name", "email"] }], order: [["lastAccessedAt", "DESC"]], limit, offset: (page - 1) * limit }); const total = await db.Enrolment.count({ where }); const rows = await Promise.all(users.map(async (enrolment) => ({ student: enrolment.User, lastActivityAt: enrolment.lastAccessedAt, ...(await gradebookForStudent(enrolment.userId, req.params.courseTrackId, { teacher: true })) }))); send(res, { items: rows, pagination: { page, limit, total } }); }));
router.post("/admin/students/:studentId/activities/:activityId/approve", authenticate, requirePermission(PERMISSIONS.GRADES_MANAGE), asyncHandler(async (req, res) => { const activity = await db.LessonSection.findByPk(req.params.activityId); if (!activity) throw new ApiError(404, "Activity not found"); const lesson = await db.Lesson.findByPk(activity.lessonId); await assertGradebookScope(req.user, lesson.trackId); const approval = await db.TeacherActivityApproval.upsert({ userId: req.params.studentId, activityId: activity.id, approvedByUserId: req.user.sub, approvedAt: new Date(), revokedAt: null, comment: req.body.comment ? cleanComment(req.body.comment) : null }); await audit(req, "activity_approval_granted", "activity", activity.id, { studentId: req.params.studentId }); send(res, approval[0]); }));
router.delete("/admin/students/:studentId/activities/:activityId/approve", authenticate, requirePermission(PERMISSIONS.GRADES_MANAGE), asyncHandler(async (req, res) => { const approval = await db.TeacherActivityApproval.findOne({ where: { userId: req.params.studentId, activityId: req.params.activityId, revokedAt: null }, include: [db.LessonSection] }); if (!approval) throw new ApiError(404, "Approval not found"); const lesson = await db.Lesson.findByPk(approval.LessonSection.lessonId); await assertGradebookScope(req.user, lesson.trackId); await approval.update({ revokedAt: new Date() }); await audit(req, "activity_approval_revoked", "activity", req.params.activityId, { studentId: req.params.studentId }); res.status(204).end(); }));
router.post("/admin/courses/:courseTrackId/students/:studentId/comments", authenticate, requirePermission(PERMISSIONS.GRADES_MANAGE), asyncHandler(async (req, res) => { await assertGradebookScope(req.user, req.params.courseTrackId); const comment = await db.TeacherGradeComment.create({ userId: req.params.studentId, courseTrackId: req.params.courseTrackId, teacherId: req.user.sub, comment: cleanComment(req.body.comment), visibility: ["student_visible", "teacher_private"].includes(req.body.visibility) ? req.body.visibility : "student_visible" }); await audit(req, "grade_comment_created", "teacher_grade_comment", comment.id, { studentId: req.params.studentId, visibility: comment.visibility }); send(res, comment, 201); }));
router.patch("/admin/grade-comments/:id", authenticate, requirePermission(PERMISSIONS.GRADES_MANAGE), asyncHandler(async (req, res) => { const comment = await db.TeacherGradeComment.findByPk(req.params.id); if (!comment) throw new ApiError(404, "Comment not found"); await assertGradebookScope(req.user, comment.courseTrackId); await comment.update({ ...(req.body.comment !== undefined ? { comment: cleanComment(req.body.comment) } : {}), ...(req.body.visibility && ["student_visible", "teacher_private"].includes(req.body.visibility) ? { visibility: req.body.visibility } : {}) }); await audit(req, "grade_comment_updated", "teacher_grade_comment", comment.id); send(res, comment); }));
export default router;
