import { Op } from "sequelize";
import { ApiError } from "../../core/errors.js";
import { db } from "../../models/index.js";
import { assertQuestionScope } from "./question.service.js";

export const questionCategorySlug = (value) => String(value || "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const valuesFrom = (body) => { const values = {}; for (const key of ["courseId", "courseTrackId", "lessonId", "topicId", "parentCategoryId", "name", "slug", "description", "sortOrder"]) if (Object.hasOwn(body, key)) values[key] = body[key]; if (values.name !== undefined) values.name = String(values.name || "").trim(); if (values.slug !== undefined) values.slug = String(values.slug || "").trim().toLowerCase(); else if (values.name) values.slug = questionCategorySlug(values.name); if (values.sortOrder !== undefined && (!Number.isInteger(values.sortOrder) || values.sortOrder < 0)) throw new ApiError(422, "sortOrder must be a non-negative integer"); return values; };
const validate = async (values, current, user, transaction) => { const effective = { ...current?.get?.({ plain: true }), ...values }; if (!effective.courseId || !effective.courseTrackId || !effective.name || !effective.slug) throw new ApiError(422, "Course, Medium, name and slug are required"); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(effective.slug)) throw new ApiError(422, "Category slug must contain lowercase letters, numbers and hyphens"); const track = await assertQuestionScope(user, effective.courseTrackId); if (track.courseId !== effective.courseId) throw new ApiError(422, "Course and Medium must match"); let lesson = null; if (effective.lessonId) { lesson = await db.Lesson.findByPk(effective.lessonId, { transaction }); if (!lesson || lesson.trackId !== track.id) throw new ApiError(422, "Lesson must belong to the selected Course and Medium"); } if (effective.topicId) { const topic = await db.Topic.findByPk(effective.topicId, { transaction }); if (!topic || (lesson && topic.lessonId !== lesson.id)) throw new ApiError(422, "Topic must belong to the selected Lesson"); const topicLesson = lesson || await db.Lesson.findByPk(topic.lessonId, { transaction }); if (!topicLesson || topicLesson.trackId !== track.id) throw new ApiError(422, "Topic must belong to the selected Course and Medium"); } if (effective.parentCategoryId) { const parent = await db.QuestionCategory.findByPk(effective.parentCategoryId, { transaction }); if (!parent || parent.courseId !== effective.courseId || parent.courseTrackId !== effective.courseTrackId || parent.status === "archived") throw new ApiError(422, "Parent Category must belong to the selected Course and Medium"); if (current) { let cursor = parent; while (cursor) { if (cursor.id === current.id) throw new ApiError(422, "Question Category parent cannot be circular"); cursor = cursor.parentCategoryId ? await db.QuestionCategory.findByPk(cursor.parentCategoryId, { transaction }) : null; } } } const existing = await db.QuestionCategory.findOne({ where: { courseTrackId: effective.courseTrackId, slug: effective.slug, id: current ? { [Op.ne]: current.id } : { [Op.ne]: null } }, transaction }); if (existing) throw new ApiError(409, "Category slug already exists in this Course and Medium"); };
export const createCategory = async (body, user) => db.sequelize.transaction(async (transaction) => { const values = valuesFrom(body); await validate(values, null, user, transaction); return db.QuestionCategory.create({ ...values, status: "draft", createdByUserId: user.sub, updatedByUserId: user.sub }, { transaction }); });
export const updateCategory = async (id, body, user) => db.sequelize.transaction(async (transaction) => { const category = await db.QuestionCategory.findByPk(id, { transaction }); if (!category) throw new ApiError(404, "Question Category not found"); await assertQuestionScope(user, category.courseTrackId); if (category.status === "archived") throw new ApiError(409, "Archived Question Category cannot be updated"); const values = valuesFrom(body); await validate(values, category, user, transaction); await category.update({ ...values, updatedByUserId: user.sub }, { transaction }); return category; });
export const archiveCategory = async (id, user) => db.sequelize.transaction(async (transaction) => { const category = await db.QuestionCategory.findByPk(id, { transaction }); if (!category) throw new ApiError(404, "Question Category not found"); await assertQuestionScope(user, category.courseTrackId); await category.update({ status: "archived", archivedAt: new Date(), updatedByUserId: user.sub }, { transaction }); return category; });
