import { Op } from "sequelize";
import { ApiError } from "../../core/errors.js";
import { db } from "../../models/index.js";
import { assertQuestionScope } from "../question-bank/question.service.js";

const gradingMethods = ["highest", "latest", "average", "first"], feedbackModes = ["immediate", "after_submission", "after_quiz_closes", "never"];
const safe = (body, fields) => Object.fromEntries(fields.filter((field) => Object.hasOwn(body, field)).map((field) => [field, body[field]]));
const number = (value, field, min, max = Infinity, nullable = true) => { if (value === null || value === undefined || value === "") { if (nullable) return null; throw new ApiError(422, `${field} is required`); } if (!Number.isFinite(Number(value)) || Number(value) < min || Number(value) > max || !Number.isInteger(Number(value))) throw new ApiError(422, `Invalid ${field}`); return Number(value); };
export const trackForActivity = async (activityId) => { const activity = await db.LessonSection.findByPk(activityId); if (!activity || activity.type !== "quiz") throw new ApiError(422, "Quiz must be linked to a Quiz activity"); const lesson = await db.Lesson.findByPk(activity.lessonId); if (!lesson) throw new ApiError(422, "Quiz activity has no valid Lesson"); return { activity, lesson }; };
export const assertQuizScope = async (user, quiz) => assertQuestionScope(user, quiz.courseTrackId);
const validateSettings = (body, current = {}) => { const values = safe(body, ["title", "description", "instructions", "availableFrom", "availableUntil", "timeLimitMinutes", "attemptsAllowed", "passPercentage", "shuffleQuestions", "shuffleOptions", "questionsPerAttempt", "gradingMethod", "feedbackMode", "showCorrectAnswers", "showScore", "showExplanations", "completionRequiresPass"]); if (values.title !== undefined) { values.title = String(values.title || "").trim().slice(0, 255); if (!values.title) throw new ApiError(422, "Quiz title is required"); } for (const field of ["timeLimitMinutes", "attemptsAllowed", "questionsPerAttempt"]) if (values[field] !== undefined) values[field] = number(values[field], field, 1); if (values.passPercentage !== undefined) { if (!Number.isFinite(Number(values.passPercentage)) || Number(values.passPercentage) < 0 || Number(values.passPercentage) > 100) throw new ApiError(422, "Invalid passPercentage"); values.passPercentage = String(values.passPercentage); } for (const field of ["shuffleQuestions", "shuffleOptions", "showCorrectAnswers", "showScore", "showExplanations", "completionRequiresPass"]) if (values[field] !== undefined) values[field] = values[field] === true; if (values.gradingMethod && !gradingMethods.includes(values.gradingMethod)) throw new ApiError(422, "Invalid gradingMethod"); if (values.feedbackMode && !feedbackModes.includes(values.feedbackMode)) throw new ApiError(422, "Invalid feedbackMode"); const from = values.availableFrom === undefined ? current.availableFrom : values.availableFrom, until = values.availableUntil === undefined ? current.availableUntil : values.availableUntil; if (from && until && new Date(until) <= new Date(from)) throw new ApiError(422, "availableUntil must be after availableFrom"); return values; };
export const loadQuiz = (id, transaction) => db.Quiz.findByPk(id, { transaction });
export const createQuiz = async (body, user) => db.sequelize.transaction(async (transaction) => { const { activity, lesson } = await trackForActivity(body.lessonSectionId); await assertQuestionScope(user, lesson.trackId); const values = validateSettings(body); const quiz = await db.Quiz.create({ ...values, lessonSectionId: activity.id, courseId: (await db.CourseTrack.findByPk(lesson.trackId, { transaction })).courseId, courseTrackId: lesson.trackId, lessonId: lesson.id, topicId: activity.topicId, title: values.title || activity.title || "Quiz", status: "draft", createdByUserId: user.sub, updatedByUserId: user.sub }, { transaction }); return quiz; });
export const updateQuiz = async (id, body, user) => db.sequelize.transaction(async (transaction) => { const quiz = await loadQuiz(id, transaction); if (!quiz) throw new ApiError(404, "Quiz not found"); await assertQuizScope(user, quiz); if (quiz.status === "archived") throw new ApiError(409, "Archived Quiz cannot be updated"); await quiz.update({ ...validateSettings(body, quiz), updatedByUserId: user.sub }, { transaction }); return quiz; });
export const candidateWhere = (quiz, query = {}) => { const where = { courseId: quiz.courseId, courseTrackId: quiz.courseTrackId, status: "published" }; for (const field of ["questionCategoryId", "lessonId", "topicId", "questionType", "difficulty"]) if (query[field]) where[field] = query[field]; if (query.search) where[Op.or] = [{ title: { [Op.like]: `%${String(query.search).replace(/[\\%_]/g, "\\$&")}%` } }, { questionText: { [Op.like]: `%${String(query.search).replace(/[\\%_]/g, "\\$&")}%` } }]; return where; };
export const matchingCount = async (quiz, rule) => db.Question.count({ where: candidateWhere(quiz, rule), include: rule.tagId ? [{ model: db.QuestionTag, as: "Tags", where: { id: rule.tagId }, through: { attributes: [] }, required: true }] : [] });
export const addQuestions = async (id, questionIds, user) => db.sequelize.transaction(async (transaction) => { const quiz = await loadQuiz(id, transaction); if (!quiz) throw new ApiError(404, "Quiz not found"); await assertQuizScope(user, quiz); if (quiz.status === "archived") throw new ApiError(409, "Archived Quiz cannot be changed"); if (!Array.isArray(questionIds) || !questionIds.length || new Set(questionIds).size !== questionIds.length) throw new ApiError(422, "questionIds must be a unique non-empty list"); const questions = await db.Question.findAll({ where: { id: { [Op.in]: questionIds }, courseId: quiz.courseId, courseTrackId: quiz.courseTrackId, status: "published" }, transaction }); if (questions.length !== questionIds.length) throw new ApiError(422, "Questions must be published and compatible with this Quiz"); const existing = await db.QuizQuestion.findAll({ where: { quizId: id, questionId: { [Op.in]: questionIds } }, transaction }); if (existing.length) throw new ApiError(409, "Question is already in this Quiz"); const max = await db.QuizQuestion.max("sortOrder", { where: { quizId: id }, transaction }) || 0; await db.QuizQuestion.bulkCreate(questions.map((question, index) => ({ quizId: id, questionId: question.id, marks: question.defaultMarks, sortOrder: max + index + 1 })), { transaction }); return db.QuizQuestion.findAll({ where: { quizId: id }, include: [{ model: db.Question, as: "Question" }], order: [["sortOrder", "ASC"]], transaction }); });
export const validatePublish = async (quiz, transaction) => { const activity = await db.LessonSection.findByPk(quiz.lessonSectionId, { transaction }); if (!activity || activity.type !== "quiz") throw new ApiError(422, "Quiz must be linked to a valid Quiz activity"); validateSettings(quiz.get({ plain: true }), quiz); const rows = await db.QuizQuestion.findAll({ where: { quizId: quiz.id }, include: [{ model: db.Question, as: "Question" }], transaction }); const rules = await db.QuizRandomRule.findAll({ where: { quizId: quiz.id }, transaction }); if (!rows.length && !rules.length) throw new ApiError(422, "Add a Question or random selection rule before publishing"); if (rows.some((row) => !row.Question || row.Question.status !== "published" || Number(row.marks) <= 0)) throw new ApiError(422, "All Quiz Questions must be published with positive marks"); for (const rule of rules) if (await matchingCount(quiz, rule) < rule.questionCount) throw new ApiError(422, "A random rule does not have enough published Questions"); const pool = rows.length + (await Promise.all(rules.map((rule) => matchingCount(quiz, rule)))).reduce((total, count) => total + count, 0); if (quiz.questionsPerAttempt && quiz.questionsPerAttempt > pool) throw new ApiError(422, "questionsPerAttempt exceeds the available Question pool"); };
