import { DataTypes } from "sequelize";
import { defineModel } from "./helpers.js";

export const defineQuestionCategory = (sequelize) => defineModel(sequelize, "QuestionCategory", { courseId: { type: DataTypes.UUID, allowNull: false }, courseTrackId: { type: DataTypes.UUID, allowNull: false }, lessonId: DataTypes.UUID, topicId: DataTypes.UUID, parentCategoryId: DataTypes.UUID, name: { type: DataTypes.STRING, allowNull: false }, slug: { type: DataTypes.STRING, allowNull: false }, description: DataTypes.TEXT, status: { type: DataTypes.ENUM("draft", "published", "unpublished", "archived"), defaultValue: "draft" }, sortOrder: { type: DataTypes.INTEGER, defaultValue: 0 }, createdByUserId: { type: DataTypes.UUID, allowNull: false }, updatedByUserId: DataTypes.UUID, archivedAt: DataTypes.DATE });
export const defineQuestion = (sequelize) => defineModel(sequelize, "Question", { questionCategoryId: { type: DataTypes.UUID, allowNull: false }, courseId: { type: DataTypes.UUID, allowNull: false }, courseTrackId: { type: DataTypes.UUID, allowNull: false }, lessonId: DataTypes.UUID, topicId: DataTypes.UUID, questionType: { type: DataTypes.STRING, allowNull: false }, title: DataTypes.STRING, questionText: { type: DataTypes.TEXT, allowNull: false }, questionTextFormat: { type: DataTypes.STRING, defaultValue: "html" }, difficulty: { type: DataTypes.ENUM("easy", "medium", "hard"), defaultValue: "medium" }, defaultMarks: { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 1 }, negativeMarks: DataTypes.DECIMAL(10, 2), generalFeedback: DataTypes.TEXT, correctFeedback: DataTypes.TEXT, incorrectFeedback: DataTypes.TEXT, explanation: DataTypes.TEXT, status: { type: DataTypes.ENUM("draft", "published", "unpublished", "archived"), defaultValue: "draft" }, version: { type: DataTypes.INTEGER, defaultValue: 1 }, createdByUserId: { type: DataTypes.UUID, allowNull: false }, updatedByUserId: DataTypes.UUID, publishedAt: DataTypes.DATE, archivedAt: DataTypes.DATE });
export const defineQuestionOption = (sequelize) => defineModel(sequelize, "QuestionOption", { questionId: { type: DataTypes.UUID, allowNull: false }, optionText: { type: DataTypes.TEXT, allowNull: false }, optionTextFormat: { type: DataTypes.STRING, defaultValue: "html" }, isCorrect: { type: DataTypes.BOOLEAN, defaultValue: false }, feedback: DataTypes.TEXT, sortOrder: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 }, matchKey: DataTypes.STRING });
export const defineQuestionAcceptedAnswer = (sequelize) => defineModel(sequelize, "QuestionAcceptedAnswer", { questionId: { type: DataTypes.UUID, allowNull: false }, answerText: { type: DataTypes.TEXT, allowNull: false }, isCaseSensitive: { type: DataTypes.BOOLEAN, defaultValue: false }, matchMode: { type: DataTypes.ENUM("exact", "normalized"), defaultValue: "normalized" }, weight: { type: DataTypes.DECIMAL(5, 2), defaultValue: 1 }, feedback: DataTypes.TEXT, sortOrder: { type: DataTypes.INTEGER, defaultValue: 0 } });
export const defineQuestionNumericAnswer = (sequelize) => defineModel(sequelize, "QuestionNumericAnswer", { questionId: { type: DataTypes.UUID, allowNull: false, unique: true }, answerValue: { type: DataTypes.DECIMAL(20, 6), allowNull: false }, toleranceType: { type: DataTypes.ENUM("absolute", "range"), defaultValue: "absolute" }, toleranceValue: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }, minimumValue: DataTypes.DECIMAL(20, 6), maximumValue: DataTypes.DECIMAL(20, 6), unit: DataTypes.STRING, feedback: DataTypes.TEXT });
export const defineQuestionMatchingPair = (sequelize) => defineModel(sequelize, "QuestionMatchingPair", { questionId: { type: DataTypes.UUID, allowNull: false }, promptText: { type: DataTypes.TEXT, allowNull: false }, matchText: { type: DataTypes.TEXT, allowNull: false }, feedback: DataTypes.TEXT, sortOrder: { type: DataTypes.INTEGER, defaultValue: 0 } });
export const defineQuestionOrderingItem = (sequelize) => defineModel(sequelize, "QuestionOrderingItem", { questionId: { type: DataTypes.UUID, allowNull: false }, itemText: { type: DataTypes.TEXT, allowNull: false }, correctPosition: { type: DataTypes.INTEGER, allowNull: false }, feedback: DataTypes.TEXT, sortOrder: { type: DataTypes.INTEGER, defaultValue: 0 } });
export const defineQuestionEssayConfig = (sequelize) => defineModel(sequelize, "QuestionEssayConfig", { questionId: { type: DataTypes.UUID, allowNull: false, unique: true }, minimumWords: DataTypes.INTEGER, maximumWords: DataTypes.INTEGER, responseFormat: { type: DataTypes.ENUM("plain_text", "rich_text"), defaultValue: "rich_text" }, gradingGuide: DataTypes.TEXT, modelAnswer: DataTypes.TEXT });
export const defineQuestionTag = (sequelize) => defineModel(sequelize, "QuestionTag", { courseId: { type: DataTypes.UUID, allowNull: false }, name: { type: DataTypes.STRING, allowNull: false }, normalizedName: { type: DataTypes.STRING, allowNull: false } });
export const defineQuestionTagAssignment = (sequelize) => defineModel(sequelize, "QuestionTagAssignment", { questionId: { type: DataTypes.UUID, allowNull: false }, questionTagId: { type: DataTypes.UUID, allowNull: false } });
