import { DataTypes } from "sequelize";
import { defineModel } from "./helpers.js";

export const defineQuiz = (sequelize) => defineModel(sequelize, "Quiz", {
  lessonSectionId: { type: DataTypes.UUID, allowNull: false, unique: true }, courseId: { type: DataTypes.UUID, allowNull: false }, courseTrackId: { type: DataTypes.UUID, allowNull: false }, lessonId: { type: DataTypes.UUID, allowNull: false }, topicId: DataTypes.UUID,
  title: { type: DataTypes.STRING, allowNull: false }, description: DataTypes.TEXT, instructions: DataTypes.TEXT, status: { type: DataTypes.ENUM("draft", "published", "unpublished", "archived"), defaultValue: "draft" },
  availableFrom: DataTypes.DATE, availableUntil: DataTypes.DATE, timeLimitMinutes: DataTypes.INTEGER, attemptsAllowed: { type: DataTypes.INTEGER, defaultValue: 1 }, passPercentage: { type: DataTypes.DECIMAL(5, 2), defaultValue: 0 }, shuffleQuestions: { type: DataTypes.BOOLEAN, defaultValue: false }, shuffleOptions: { type: DataTypes.BOOLEAN, defaultValue: false }, questionsPerAttempt: DataTypes.INTEGER,
  gradingMethod: { type: DataTypes.ENUM("highest", "latest", "average", "first"), defaultValue: "highest" }, feedbackMode: { type: DataTypes.ENUM("immediate", "after_submission", "after_quiz_closes", "never"), defaultValue: "after_submission" }, showCorrectAnswers: { type: DataTypes.BOOLEAN, defaultValue: false }, showScore: { type: DataTypes.BOOLEAN, defaultValue: true }, showExplanations: { type: DataTypes.BOOLEAN, defaultValue: false }, completionRequiresPass: { type: DataTypes.BOOLEAN, defaultValue: false },
  createdByUserId: { type: DataTypes.UUID, allowNull: false }, updatedByUserId: DataTypes.UUID, publishedAt: DataTypes.DATE, archivedAt: DataTypes.DATE,
});
export const defineQuizQuestion = (sequelize) => defineModel(sequelize, "QuizQuestion", { quizId: { type: DataTypes.UUID, allowNull: false }, questionId: { type: DataTypes.UUID, allowNull: false }, marks: { type: DataTypes.DECIMAL(10, 2), allowNull: false }, sortOrder: { type: DataTypes.INTEGER, allowNull: false }, isRequired: { type: DataTypes.BOOLEAN, defaultValue: true } });
export const defineQuizRandomRule = (sequelize) => defineModel(sequelize, "QuizRandomRule", { quizId: { type: DataTypes.UUID, allowNull: false }, questionCategoryId: DataTypes.UUID, lessonId: DataTypes.UUID, topicId: DataTypes.UUID, questionType: DataTypes.STRING, difficulty: DataTypes.STRING, tagId: DataTypes.UUID, questionCount: { type: DataTypes.INTEGER, allowNull: false }, marksPerQuestion: { type: DataTypes.DECIMAL(10, 2), allowNull: false }, sortOrder: { type: DataTypes.INTEGER, allowNull: false } });
